{
 "title": "Wireguard",
 "description": "Metrics for Wireguard VPN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Connected Clients (SI)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(wireguard_received_bytes_total[$__rate_interval])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(wireguard_sent_bytes_total[$__rate_interval])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(wireguard_received_bytes_total[$__rate_interval])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes / node_filesystem_size_bytes",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}}" },
    { "expr": "node_load5", "legendFormat": "{{__name__}}" },
    { "expr": "node_load15", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Latest Handshakes",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "time() - wireguard_latest_handshake_seconds",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}